features: equal
planetscale/vtprotobuf pull request #28
Opened 2022-02-23 16:09 UTC by fenollp

This begins the work of porting [a variant of] gogo's [equal plugin](https://github.com/gogo/protobuf/blob/b03c65ea87cdc3521ede29f62fe3ce239267c1bc/plugin/equal/equal.go)

An unrolled non-`reflect`ive implementation of `proto.Equal` is about twice faster in our testing.

Note: this is WIP. It is hard to test right now (I am working on a CI PR that should help here) mainly because this command cannot be used with forks:
```shell
go install github.com/planetscale/vtprotobuf/cmd/protoc-gen-go-vtproto@latest
```
Any help around this is very welcomed!

2022-02-23 17:29 UTC, vmg commented
I think you're off to a good start but you're definitely going to need more tests for this feature!

>  It is hard to test right now (I am working on a CI PR that should help here) mainly because this command cannot be used with forks

Yeah, that's a limitation with `go install`. Your best bet is cloning your fork locally and then calling `go install` pointing at the local clone. That should get you going.

2022-04-08 16:34 UTC, fenollp commented
@vmg Ready for review! :)

2022-04-12 08:13 UTC, vmg requested changes
This looks _great_. Thank you so much for the extensive tests. Could you please fix the `unknownFields` comparison?

2022-04-12 08:13 UTC, vmg commented on features/equal/equal.go
> +	p.P(`return string(this.unknownFields) == string(that.unknownFields)`)
This should be `bytes.Equal`. It doesn't make much sense to force a `string` cast for comparison.

2022-04-12 08:15 UTC, vmg approved these changes

2022-04-12 08:15 UTC, merged